### ISSUE TITLE
リンクをonClickではなくLinkで

### ISSUE THREAD

**Issue by schola-ymok** [schola-ymok/schola#21]
そうしないとブラウザで「新しいタブで開く」が使えず不便

**Comment by fj-ymok** [comment]
ひととおり対応済
ボタンはonClickで、文字のリンクはLinkで対応
next/Linkとmui/Linkで混同するので要注意

**Comment by schola-ymok** [comment]
概ね対応済み。文字のリンクはLink(next/Link)で、ボタンはonClickでrouter.pushで対応
