### ISSUE TITLE
Rankパネルの横幅が崩れる

### ISSUE THREAD

**Issue by schola-ymok** [schola-ymok/schola#6]

**Comment by fj-ymok** [comment]
下記コミットで対応。flexShrinkを0に。
[ae092c89a5e703859435581a73483daf649243c8](https://github.com/schola-ymok/schola/commit/ae092c89a5e703859435581a73483daf649243c8)

**Comment by schola-ymok** [comment]
下記コミットで対応。flexShrink:0で解決。
https://github.com/schola-ymok/schola/commit/ae092c89a5e703859435581a73483daf649243c8
